// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3cEhjK3x7sNT3KZeMkSHGzQrXn7p2Brc',
    appId: '1:594143531503:web:8d7d40b96f14289842661a',
    messagingSenderId: '594143531503',
    projectId: 'chatappflutter-8b45b',
    authDomain: 'chatappflutter-8b45b.firebaseapp.com',
    storageBucket: 'chatappflutter-8b45b.appspot.com',
    measurementId: 'G-JVH04YE5DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBzHiHasZ53_9ndJfEliGIG-1anJYxLUs',
    appId: '1:594143531503:android:2245245f015debf442661a',
    messagingSenderId: '594143531503',
    projectId: 'chatappflutter-8b45b',
    storageBucket: 'chatappflutter-8b45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8bV1S8Uu7wcd67yLRiEzt-g_vncEmYEk',
    appId: '1:594143531503:ios:f8dbd1862fd9146642661a',
    messagingSenderId: '594143531503',
    projectId: 'chatappflutter-8b45b',
    storageBucket: 'chatappflutter-8b45b.appspot.com',
    iosBundleId: 'xccom.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8bV1S8Uu7wcd67yLRiEzt-g_vncEmYEk',
    appId: '1:594143531503:ios:148043548b6986b042661a',
    messagingSenderId: '594143531503',
    projectId: 'chatappflutter-8b45b',
    storageBucket: 'chatappflutter-8b45b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
